@include('templates.formulario.input', ['label' => 'CPF', 'input' => 'cpf' , 'attributes' => ['placeholder' => 'CPF']])
@include('templates.formulario.input', ['label' => 'Nome do Usuário', 'input' => 'name' , 'attributes' => ['placeholder' => 'Nome do Usuário']])
@include('templates.formulario.input', ['label' => 'Telefone', 'input' => 'phone', 'attributes' => ['placeholder' => 'Telefone']])
@include('templates.formulario.input', ['label' => 'E-mail', 'input' => 'email', 'attributes' => ['placeholder' => 'E-mail']])
@include('templates.formulario.password', ['label' => 'Senha', 'input' => 'password', 'attributes' => ['placeholder' => 'Senha']])